name: generate-metrics
on:
    workflow_dispatch:

jobs:
    hello:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: show repo
              run: ls -lah && pwd
